### ISSUE TITLE
Planar/interleaved option?

### ISSUE THREAD

**Issue by dy** [raymond-h/pcm-format#3]
There’s interesting difference between how node-speaker and web-audio-api represent buffered PCM data. Node-speaker takes input data in interleaved form, as `LRLRLRLR...`, whereas web-audio, probably as well as some other libs, take it in planar form as `LLLLLLRRRRRR`.
There’s [explanation in MDN article](https://developer.mozilla.org/en-US/docs/Web/API/Web_Audio_API/Basic_concepts_behind_Web_Audio_API#Planar_versus_interleaved_buffers).

In that, it might be useful to be able to perform conversion between planar/interleaved forms, as

``` js
var formatter = new PCMFormat({interleaved: false},{interleaved: true});
```

Another matter, btw, is providing consistent output buffer size, dependless of input buffer size. E. g. some input PCM-stream may send frames with 256 samples, whereas we need 1024 samples. But that is possibly another feature-request or another package at all.

**Comment by raymond-h** [comment]
When it does matter, pretty much all other modules use interleaved format, because that works nicely with streams, since you typically don't know when exactly a stream will end. This module, at this moment, is one case where it indeed does not matter, as it merely converts single samples, regardless of which channel it is part of; this is also why this module does not take a `channels` option. A separate module that does handle converting between planar and interleaved formats (and maybe even converts between channel counts) would be great, however.

I personally think it's a bad idea to depend on output chunks to be of specific sizes, unless you're directly trying to consume a stream by registering `"data"` handler and the likes, in which case, there are already modules out there for re-splitting chunks so they're all a consistent size.

**Comment by dy** [comment]
Ah, got it. Alright, probably I should look up for some such module, or implement it.
